update 2026-07-19 16:02:16

diff --git a/daed/files/daed-guard b/daed/files/daed-guard
--- a/daed/files/daed-guard
+++ b/daed/files/daed-guard
@@ -2,5 +2,8 @@
 
 . /usr/share/daed/cleanup.sh
 
-daed_cleanup_runtime
+if ! daed_cleanup_runtime; then
+	echo "daed: stale network state could not be removed" >&2
+	exit 1
+fi
 exec /usr/bin/daed "$@"
