update 2023-06-03 16:20:05

diff --git a/homeproxy/root/etc/init.d/homeproxy b/homeproxy/root/etc/init.d/homeproxy
--- a/homeproxy/root/etc/init.d/homeproxy
+++ b/homeproxy/root/etc/init.d/homeproxy
@@ -42,21 +42,19 @@ start_service() {
 	fi
 
 	mkdir -p "$RUN_DIR"
-	ucode -S "$HP_DIR/scripts/generate_sing-box.uc" 2>>"$LOG_PATH"
-
-	local inbounds="$(jsonfilter -i "$RUN_DIR/sing-box.json" -e "@.inbounds[@.tag!='dns-in']" 2>"/dev/null")"
-	if [ ! -e "$RUN_DIR/sing-box.json" ]; then
-		log "Error: failed to generate configuration."
-		return 1
-	elif [ -z "$inbounds" ]; then
-		log "Error: no valid inbound found."
-		return 1
-	elif ! "$PROG" check --config "$RUN_DIR/sing-box.json" 2>>"$LOG_PATH"; then
-		log "Error: wrong configuration detected."
-		return 1
-	fi
 
 	if [ "$outbound_node" != "nil" ]; then
+		# Generate/Validate client config
+		ucode -S "$HP_DIR/scripts/generate_client.uc" 2>>"$LOG_PATH"
+
+		if [ ! -e "$RUN_DIR/sing-box-c.json" ]; then
+			log "Error: failed to generate client configuration."
+			return 1
+		elif ! "$PROG" check --config "$RUN_DIR/sing-box-c.json" 2>>"$LOG_PATH"; then
+			log "Error: wrong client configuration detected."
+			return 1
+		fi
+
 		# Auto update
 		local auto_update auto_update_time
 		config_get_bool auto_update "subscription" "auto_update" "0"
@@ -66,10 +64,9 @@ start_service() {
 			/etc/init.d/cron restart
 		fi
 
+		# DNSMasq rules
 		local ipv6_support
 		config_get_bool ipv6_support "config" "ipv6_support" "0"
-
-		# DNSMasq rules
 		local dns_port china_dns_server china_dns_port
 		config_get dns_port "infra" "dns_port" "5333"
 		mkdir -p "$DNSMASQ_DIR"
@@ -116,7 +113,7 @@ start_service() {
 		fi
 		/etc/init.d/dnsmasq restart >"/dev/null" 2>&1
 
-		# Setup firewall
+		# Setup routing table
 		local table_mark
 		config_get table_mark "infra" "table_mark" "100"
 		case "$proxy_mode" in
@@ -152,57 +149,91 @@ start_service() {
 			;;
 		esac
 
-		utpl -S "$HP_DIR/scripts/firewall_post.ut" > "$RUN_DIR/fw4_post.nft"
+		# sing-box (client)
+		procd_open_instance "sing-box-c"
+
+		procd_set_param command "$PROG"
+		procd_append_param command run --config "$RUN_DIR/sing-box-c.json"
+
+		if [ -x "/sbin/ujail" ] && [ "$routing_mode" != "custom" ] && ! grep -Eq '"type": "(wireguard|tun)"' "$RUN_DIR/sing-box-c.json"; then
+			procd_add_jail "sing-box-c" log procfs
+			procd_add_jail_mount "$RUN_DIR/sing-box-c.json"
+			procd_add_jail_mount_rw "$RUN_DIR/sing-box-c.log"
+			procd_add_jail_mount "$HP_DIR/certs/"
+			procd_add_jail_mount "/etc/ssl/"
+			procd_set_param capabilities "/etc/capabilities/homeproxy.json"
+			procd_set_param no_new_privs 1
+			procd_set_param user sing-box
+			procd_set_param group sing-box
+		fi
+
+		procd_set_param limits core="unlimited"
+		procd_set_param limits nofile="1000000 1000000"
+		procd_set_param stderr 1
+		procd_set_param respawn
+
+		procd_close_instance
+
+		# chinadns-ng
+		if [ -n "$china_dns_server" ]; then
+			local wandns="$(ifstatus wan | jsonfilter -e '@["dns-server"][0]' || echo "119.29.29.29")"
+			case "$china_dns_server" in
+			"wan") china_dns_server="$wandns" ;;
+			"wan_114") china_dns_server="$wandns,114.114.114.114" ;;
+			esac
+
+			procd_open_instance "chinadns-ng"
+
+			procd_set_param command "/usr/bin/chinadns-ng"
+			procd_append_param command --bind-port "$china_dns_port"
+			procd_append_param command --china-dns "$china_dns_server"
+			procd_append_param command --trust-dns "127.0.0.1#$dns_port"
+			procd_append_param command --ipset-name4 "inet@fw4@homeproxy_mainland_addr_v4"
+			procd_append_param command --ipset-name6 "inet@fw4@homeproxy_mainland_addr_v6"
+			procd_append_param command --gfwlist-file "$HP_DIR/resources/gfw_list.txt"
+			[ "$ipv6_support" -eq "1" ] || procd_append_param command --no-ipv6=tC
+
+			if [ -x "/sbin/ujail" ]; then
+				procd_add_jail "chinadns-ng" log
+				procd_add_jail_mount "$HP_DIR/resources/gfw_list.txt"
+				procd_set_param capabilities "/etc/capabilities/homeproxy.json"
+				procd_set_param no_new_privs 1
+				procd_set_param user sing-box
+				procd_set_param group sing-box
+			fi
+
+			procd_set_param limits core="unlimited"
+			procd_set_param limits nofile="1000000 1000000"
+			procd_set_param stderr 1
+			procd_set_param respawn
+
+			procd_close_instance
+		fi
 	fi
 
-	utpl -S "$HP_DIR/scripts/firewall_pre.ut" > "$RUN_DIR/fw4_pre.nft"
-	fw4 reload >"/dev/null" 2>&1
+	if [ "$server_enabled" = "1" ]; then
+		# Generate/Validate server config
+		ucode -S "$HP_DIR/scripts/generate_server.uc" 2>>"$LOG_PATH"
 
-	# sing-box
-	procd_open_instance "sing-box"
+		if [ ! -e "$RUN_DIR/sing-box-s.json" ]; then
+			log "Error: failed to generate server configuration."
+			return 1
+		elif ! "$PROG" check --config "$RUN_DIR/sing-box-s.json" 2>>"$LOG_PATH"; then
+			log "Error: wrong server configuration detected."
+			return 1
+		fi
 
-	procd_set_param command "$PROG"
-	procd_append_param command run --config "$RUN_DIR/sing-box.json"
+		# sing-box (server)
+		procd_open_instance "sing-box-s"
 
-	if [ -x "/sbin/ujail" ] && [ "$routing_mode" != "custom" ] && ! grep -Eq '"type": "(wireguard|tun)"' "$RUN_DIR/sing-box.json"; then
-		procd_add_jail "sing-box" log procfs
-		procd_add_jail_mount "$RUN_DIR/sing-box.json"
-		procd_add_jail_mount_rw "$RUN_DIR/sing-box.log"
-		procd_set_param capabilities "/etc/capabilities/homeproxy.json"
-		procd_set_param no_new_privs 1
-		procd_set_param user sing-box
-		procd_set_param group sing-box
-	fi
-
-	procd_set_param limits core="unlimited"
-	procd_set_param limits nofile="1000000 1000000"
-	procd_set_param stderr 1
-	procd_set_param respawn
-
-	procd_close_instance
-
-	# chinadns-ng
-	if [ -n "$china_dns_server" ]; then
-		local wandns="$(ifstatus wan | jsonfilter -e '@["dns-server"][0]' || echo "119.29.29.29")"
-		case "$china_dns_server" in
-		"wan") china_dns_server="$wandns" ;;
-		"wan_114") china_dns_server="$wandns,114.114.114.114" ;;
-		esac
-
-		procd_open_instance "chinadns-ng"
-
-		procd_set_param command "/usr/bin/chinadns-ng"
-		procd_append_param command --bind-port "$china_dns_port"
-		procd_append_param command --china-dns "$china_dns_server"
-		procd_append_param command --trust-dns "127.0.0.1#$dns_port"
-		procd_append_param command --ipset-name4 "inet@fw4@homeproxy_mainland_addr_v4"
-		procd_append_param command --ipset-name6 "inet@fw4@homeproxy_mainland_addr_v6"
-		procd_append_param command --gfwlist-file "$HP_DIR/resources/gfw_list.txt"
-		[ "$ipv6_support" -eq "1" ] || procd_append_param command --no-ipv6=tC
+		procd_set_param command "$PROG"
+		procd_append_param command run --config "$RUN_DIR/sing-box-s.json"
 
 		if [ -x "/sbin/ujail" ]; then
-			procd_add_jail "chinadns-ng" log
-			procd_add_jail_mount "$HP_DIR/resources/gfw_list.txt"
+			procd_add_jail "sing-box-s" log procfs
+			procd_add_jail_mount "$RUN_DIR/sing-box-s.json"
+			procd_add_jail_mount_rw "$RUN_DIR/sing-box-s.log"
+			procd_add_jail_mount "$HP_DIR/certs/"
 			procd_set_param capabilities "/etc/capabilities/homeproxy.json"
 			procd_set_param no_new_privs 1
 			procd_set_param user sing-box
@@ -224,10 +255,22 @@ start_service() {
 	procd_close_instance
 
 	# Update permissions for ujail
-	echo > "$RUN_DIR/sing-box.log"
-	chown sing-box:sing-box "$RUN_DIR/sing-box.log"
-	chown sing-box:sing-box "$RUN_DIR/sing-box.json"
-	chmod 0644 "$HP_DIR/resources/gfw_list.txt"
+	if [ "$outbound_node" != "nil" ]; then
+		echo > "$RUN_DIR/sing-box-c.log"
+		chown sing-box:sing-box "$RUN_DIR/sing-box-c.log"
+		chown sing-box:sing-box "$RUN_DIR/sing-box-c.json"
+		chmod 0644 "$HP_DIR/resources/gfw_list.txt"
+	fi
+	if [ "$server_enabled" = "1" ]; then
+		echo > "$RUN_DIR/sing-box-s.log"
+		chown sing-box:sing-box "$RUN_DIR/sing-box-s.log"
+		chown sing-box:sing-box "$RUN_DIR/sing-box-s.json"
+	fi
+
+	# Setup firewall
+	[ "$outbound_node" = "nil" ] || utpl -S "$HP_DIR/scripts/firewall_post.ut" > "$RUN_DIR/fw4_post.nft"
+	utpl -S "$HP_DIR/scripts/firewall_pre.ut" > "$RUN_DIR/fw4_pre.nft"
+	fw4 reload >"/dev/null" 2>&1
 
 	log "$(sing-box version | awk 'NR==1{print $1,$3}') started."
 }
@@ -289,7 +332,8 @@ stop_service() {
 	rm -rf "$DNSMASQ_DIR/../dnsmasq-homeproxy.conf" "$DNSMASQ_DIR"
 	/etc/init.d/dnsmasq restart >"/dev/null" 2>&1
 
-	rm -f "$RUN_DIR/sing-box.json" "$RUN_DIR/sing-box.log"
+	rm -f "$RUN_DIR/sing-box-c.json" "$RUN_DIR/sing-box-c.log" \
+		"$RUN_DIR/sing-box-s.json" "$RUN_DIR/sing-box-s.log"
 
 	log "Service stopped."
 }
