update 2025-08-28 12:26:30

diff --git a/luci-app-fchomo/Makefile b/luci-app-fchomo/Makefile
--- a/luci-app-fchomo/Makefile
+++ b/luci-app-fchomo/Makefile
@@ -33,6 +33,27 @@ endef
 
 PKG_UNPACK=$(CURDIR)/.prepare.sh $(PKG_NAME) $(CURDIR) $(PKG_BUILD_DIR)
 
+define Package/luci-app-fchomo/postinst
+#!/bin/sh
+# openwrt version check
+export REVISION VERSION_NUMBER ARCH_PACKAGES
+if [ -n "$$IPKG_INSTROOT" ]; then
+	# building
+	REVISION=$$($$TOPDIR/scripts/getver.sh)
+	REVISION=$$(echo "$$REVISION" | cut -f1 -d'-' | sed 's|[a-z]||gi')
+else
+	# system
+	REVISION=$$(ubus call system board | jsonfilter -qe '@.release.revision' | cut -f1 -d'-' | sed 's|[a-z]||gi')
+fi
+
+[ "$$REVISION" -ge 28158 ] || { 2>&1 echo "Minimum OpenWrt version required is 24.10."; exit 1; }
+# https://archive.openwrt.org/releases/**/version.buildinfo
+# r?????-??????????    25.??.?-rc1
+# r28158-d276b4c91a    24.10.0-rc1
+# r23069-e2701e0f33    23.05.0-rc1
+exit 0
+endef
+
 define Package/luci-app-fchomo/prerm
 #!/bin/sh
 uci delete firewall.fchomo_pre
