update 2024-05-11 00:21:41

diff --git a/mwan3/files/usr/sbin/mwan3 b/mwan3/files/usr/sbin/mwan3
--- a/mwan3/files/usr/sbin/mwan3
+++ b/mwan3/files/usr/sbin/mwan3
@@ -5,62 +5,75 @@
 . /lib/functions/network.sh
 . /lib/mwan3/mwan3.sh
 
-command_help() {
-	local cmd="$1"
-	local help="$2"
-
-	echo "$(printf "%-25s%s" "${cmd}" "${help}")"
-}
-
 help()
 {
 	cat <<EOF
 Syntax: mwan3 [command]
 
 Available commands:
+	start           Load iptables rules, ip rules and ip routes
+	stop            Unload iptables rules, ip rules and ip routes
+	restart         Reload iptables rules, ip rules and ip routes
+	ifup <iface>    Load rules and routes for specific interface
+	ifdown <iface>  Unload rules and routes for specific interface
+	interfaces      Show interfaces status
+	policies        Show currently active policy
+	connected       Show directly connected networks
+	rules           Show active rules
+	status          Show all status
+
 EOF
-	command_help "start" "Load iptables rules, ip rules and ip routes"
-	command_help "stop" "Unload iptables rules, ip rules and ip routes"
-	command_help "restart" "Reload iptables rules, ip rules and ip routes"
-	command_help "ifup <iface>" "Load rules and routes for specific interface"
-	command_help "ifdown <iface>" "Unload rules and routes for specific interface"
-	command_help "interfaces" "Show interfaces status"
-	command_help "policies" "Show currently active policy"
-	command_help "connected" "Show directly connected networks"
-	command_help "rules" "Show active rules"
-	command_help "status" "Show all status"
-	command_help "internal <ipv4|ipv6>" "Show internal configuration <default: ipv4>"
-	command_help "use <iface> <cmd>" "Run a command bound to <iface> and avoid mwan3 rules"
 }
 
-ifdown() {
+ifdown()
+{
 	if [ -z "$1" ]; then
-		echo "Error: Expecting interface. Usage: mwan3 ifdown <interface>"
-		exit 0
+		echo "Error: Expecting interface. Usage: mwan3 ifdown <interface>" && exit 0
 	fi
 
 	if [ -n "$2" ]; then
-		echo "Error: Too many arguments. Usage: mwan3 ifdown <interface>"
-		exit 0
+		echo "Error: Too many arguments. Usage: mwan3 ifdown <interface>" && exit 0
 	fi
 
-	mwan3_interface_hotplug_shutdown "$1" 1
+	ACTION=ifdown INTERFACE=$1 /sbin/hotplug-call iface
+
+	kill $(pgrep -f "mwan3track $1 $2") &> /dev/null
+	mwan3_track_clean $1
 }
 
-ifup() {
-	. /etc/init.d/mwan3
+ifup()
+{
+	local device enabled up l3_device status
+
+	config_load mwan3
+	config_get_bool enabled globals 'enabled' 0
+	[ ${enabled} -gt 0 ] || {
+		echo "The service mwan3 is global disabled."
+		echo "Please execute \"/etc/init.d/mwan3 start\" first."
+		exit 1
+	}
 
 	if [ -z "$1" ]; then
-		echo "Expecting interface. Usage: mwan3 ifup <interface>"
-		exit 0
+		echo "Expecting interface. Usage: mwan3 ifup <interface>" && exit 0
 	fi
 
 	if [ -n "$2" ]; then
-		echo "Too many arguments. Usage: mwan3 ifup <interface>"
-		exit 0
+		echo "Too many arguments. Usage: mwan3 ifup <interface>" && exit 0
 	fi
 
-	mwan3_ifup "$1" "cmd"
+	status=$(ubus -S call network.interface.$1 status)
+	[ -n "$status" ] && {
+		json_load "$status"
+		json_get_vars up l3_device 
+	}
+
+	config_get enabled "$1" enabled 0
+
+	if [ "$up" = "1" ] \
+		&& [ -n "$l3_device" ] \
+		&& [ "$enabled" = "1" ]; then
+		ACTION=ifup INTERFACE=$1 DEVICE=$l3_device /sbin/hotplug-call iface
+	fi
 }
 
 interfaces()
@@ -69,40 +82,37 @@ interfaces()
 
 	echo "Interface status:"
 	config_foreach mwan3_report_iface_status interface
-	echo
+	echo -e
 }
 
 policies()
 {
 	echo "Current ipv4 policies:"
 	mwan3_report_policies_v4
-	echo
-	[ $NO_IPV6 -ne 0 ] && return
+	echo -e
 	echo "Current ipv6 policies:"
 	mwan3_report_policies_v6
-	echo
+	echo -e
 }
 
 connected()
 {
 	echo "Directly connected ipv4 networks:"
 	mwan3_report_connected_v4
-	echo
-	[ $NO_IPV6 -ne 0 ] && return
+	echo -e
 	echo "Directly connected ipv6 networks:"
 	mwan3_report_connected_v6
-	echo
+	echo -e
 }
 
 rules()
 {
 	echo "Active ipv4 user rules:"
 	mwan3_report_rules_v4
-	echo
-	[ $NO_IPV6 -ne 0 ] && return
+	echo -e
 	echo "Active ipv6 user rules:"
 	mwan3_report_rules_v6
-	echo
+	echo -e
 }
 
 status()
@@ -113,136 +123,86 @@ status()
 	rules
 }
 
-internal()
+start()
 {
-	local family="$1"
-	local dash="-------------------------------------------------"
+	local enabled
 
-	if [ -f "/etc/openwrt_release" ]; then
-		. /etc/openwrt_release
-	fi
+	uci_toggle_state mwan3 globals enabled "1"
 
-	local ipt ip output
+	config_load mwan3
+	config_foreach ifup interface
+}
 
-	if [ "$family" = "ipv6" ]; then
-		ipt="$IPT6"
-		ip="$IP6"
-	else
-		ipt="$IPT4"
-		ip="$IP4"
-	fi
+stop()
+{
+	local ipset route rule table IP IPT pid
 
-	echo "Software-Version"
-	echo "$dash"
+	mwan3_lock "command" "mwan3"
 
-	if [ "$DISTRIB_RELEASE" != "" ]; then
-		echo "OpenWrt - $DISTRIB_RELEASE"
-	else
-		echo "OpenWrt - unknown"
-	fi
-
-	echo ""
-	echo "Output of \"$ip a show\""
-	echo "$dash"
-	output="$($ip a show)"
-	if [ "$output" != "" ]; then
-		echo "$output"
-	else
-		echo "No data found"
-	fi
-
-	echo ""
-	echo "Output of \"$ip route show\""
-	echo "$dash"
-	output="$($ip route show)"
-	if [ "$output" != "" ]; then
-		echo "$output"
-	else
-		echo "No data found"
-	fi
-
-	echo ""
-	echo "Output of \"$ip rule show\""
-	echo "$dash"
-	output="$($ip rule show)"
-	if [ "$output" != "" ]; then
-		echo "$output"
-	else
-		echo "No data found"
-	fi
-
-	echo ""
-	echo "Output of \"$ip route list table 1-250\""
-	echo "$dash"
-	local dump=0
-	for i in $(seq 1 250); do
-		output=$($ip route list table $i 2>/dev/null)
-		if [ "$output" != "" ];then
-			dump=1
-			echo "Routing table $i:"
-			echo "$output"
-			echo ""
-		fi
+	for pid in $(pgrep -f "mwan3rtmon"); do
+		kill -TERM "$pid" > /dev/null 2>&1
+		sleep 1
+		kill -KILL "$pid" > /dev/null 2>&1
 	done
-	if [ "$dump" = "0" ]; then
-		echo "No data found"
-		echo ""
-	fi
 
-	echo "Output of \"$ipt -L -v -n\""
-	echo "$dash"
-	output="$($ipt -L -v -n)"
-	if [ "$output" != "" ]; then
-		echo "$output"
-	else
-		echo "No data found"
-	fi
-}
+	for pid in $(pgrep -f "mwan3track"); do
+		kill -TERM "$pid" > /dev/null 2>&1
+		sleep 1
+		kill -KILL "$pid" > /dev/null 2>&1
+	done
 
-start() {
-	/etc/init.d/mwan3 enable
-	/etc/init.d/mwan3 start
-}
+	config_load mwan3
+	config_foreach mwan3_track_clean interface
 
-stop() {
-	/etc/init.d/mwan3 disable
-	/etc/init.d/mwan3 stop
+	for IP in "$IP4" "$IP6"; do
+
+		for route in $(seq 1 $MWAN3_INTERFACE_MAX); do
+			$IP route flush table $route &> /dev/null
+		done
+
+		for rule in $($IP rule list | egrep '^[1-2][0-9]{3}\:' | cut -d ':' -f 1); do
+			$IP rule del pref $rule &> /dev/null
+		done
+	done
+
+	for IPT in "$IPT4" "$IPT6"; do
+
+		$IPT -D PREROUTING -j mwan3_hook &> /dev/null
+		$IPT -D OUTPUT -j mwan3_hook &> /dev/null
+
+		for table in $($IPT -S | awk '{print $2}' | grep mwan3 | sort -u); do
+			$IPT -F $table &> /dev/null
+		done
+
+		for table in $($IPT -S | awk '{print $2}' | grep mwan3 | sort -u); do
+			$IPT -X $table &> /dev/null
+		done
+	done
+
+	for ipset in $($IPS -n list | grep mwan3_); do
+		$IPS -q destroy $ipset
+	done
+
+	for ipset in $($IPS -n list | grep mwan3 | grep -E '_v4|_v6'); do
+		$IPS -q destroy $ipset
+	done
+
+	mwan3_unlock "command" "mwan3"
+
+	mwan3_lock_clean
+	rm -rf $MWAN3_STATUS_DIR $MWAN3TRACK_STATUS_DIR
+
+	uci_toggle_state mwan3 globals enabled "0"
 }
 
 restart() {
-	/etc/init.d/mwan3 enable
-	/etc/init.d/mwan3 stop
-	/etc/init.d/mwan3 start
-}
-
-use() {
-	# Run a command with the device, src_ip and fwmark set to avoid processing by mwan3
-	# firewall rules
-
-	local interface device src_ip family
-	mwan3_init
-
-	interface=$1 ; shift
-	[ -z "$*" ] && echo "no command specified for mwan3 use" && return
-	network_get_device device $interface
-	[ -z "$device" ] && echo "could not find device for $interface" && return
-
-	mwan3_get_src_ip src_ip $interface
-	[ -z "$src_ip" ] && echo "could not find src_ip for $interface" && return
-
-	config_get family $interface family
-	[ -z "$family" ] && echo "could not find family for $interface. Using ipv4." && family='ipv4'
-
-	echo "Running '$*' with DEVICE=$device SRCIP=$src_ip FWMARK=$MMX_DEFAULT FAMILY=$family"
-	# shellcheck disable=SC2048
-	FAMILY=$family DEVICE=$device SRCIP=$src_ip FWMARK=$MMX_DEFAULT LD_PRELOAD=/lib/mwan3/libwrap_mwan3_sockopt.so.1.0 $*
-
+	stop
+	start
 }
 
 case "$1" in
-	ifup|ifdown|interfaces|policies|connected|rules|status|start|stop|restart|use|internal)
+	ifup|ifdown|interfaces|policies|connected|rules|status|start|stop|restart)
 		mwan3_init
-		# shellcheck disable=SC2048
 		$*
 	;;
 	*)
